In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
import seaborn as sbn
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer
from math import ceil

import scipy.stats as stats
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

import matplotlib.pyplot as plt

from pandas.plotting import scatter_matrix

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.model_selection import train_test_split, KFold
from sklearn.preprocessing import StandardScaler
from sklearn.base import clone
import scipy.stats as scs
import statsmodels.api as sm




from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score


import timeit
import datetime as dt

import pandasql as ps

In [2]:
houston_temp = pd.read_csv('~/Desktop/capstone2/Houston_weather.csv')

In [3]:
houston_temp.head()

Temp_avg  Temp_min  Dew_max  Dew_avg  Dew_min  Hum_max  Hum_avg  Hum_min  \
0      57.5        53       58     46.3       36       93     68.1       45   
1      62.5        60       63     60.2       58       97     92.4       87   
2      59.0        54       58     51.1       39       97     77.4       40   
3      55.9        45       43     36.3       32       77     51.1       25   
4      58.1        45       50     44.8       41       93     65.7       32   

   Wind_max  Wind_avg  Wind_min  Pres_max  Pres_avg  Pres_min  Precipitation  \
0        14       8.2         0      30.1      29.9      29.7           0.00   
1        12       4.8         0      29.7      29.6      29.6           0.28   
2        22       7.9         0      30.1      29.8      29.7           0.03   
3        12       6.0         0      30.3      30.3      30.1           0.00   
4        15       7.5         0      30.4      30.3      30.2           0.00   

       Date  
0  2020-1-1  
1  2020-1-2  
2  2020-1-3  
3  2020-1-4  
4  2020-1-5

In [4]:
houston_temp.shape

(365, 16)

In [5]:
houston_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Temp_avg       365 non-null    float64
 1   Temp_min       365 non-null    int64  
 2   Dew_max        365 non-null    int64  
 3   Dew_avg        365 non-null    float64
 4   Dew_min        365 non-null    int64  
 5   Hum_max        365 non-null    int64  
 6   Hum_avg        365 non-null    float64
 7   Hum_min        365 non-null    int64  
 8   Wind_max       365 non-null    int64  
 9   Wind_avg       365 non-null    float64
 10  Wind_min       365 non-null    int64  
 11  Pres_max       365 non-null    float64
 12  Pres_avg       365 non-null    float64
 13  Pres_min       365 non-null    float64
 14  Precipitation  365 non-null    float64
 15  Date           365 non-null    object 
dtypes: float64(8), int64(7), object(1)
memory usage: 45.8+ KB


In [6]:
houston_temp.columns

Index(['Temp_avg', 'Temp_min', 'Dew_max', 'Dew_avg', 'Dew_min', 'Hum_max',
       'Hum_avg', 'Hum_min', 'Wind_max', 'Wind_avg', 'Wind_min', 'Pres_max',
       'Pres_avg', 'Pres_min', 'Precipitation', 'Date'],
      dtype='object')

In [7]:
houston_temp_24= pd.DataFrame(np.repeat(houston_temp.values, 24, axis =0,  ))

In [8]:
houston_temp_24.head(50)

0   1   2     3   4   5     6   7   8    9  10    11    12    13    14  \
0   57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
1   57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
2   57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
3   57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
4   57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
5   57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
6   57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
7   57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
8   57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
9   57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
10  57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
11  57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
12  57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
13  57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
14  57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
15  57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
16  57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
17  57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
18  57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
19  57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
20  57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
21  57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
22  57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
23  57.5  53  58  46.3  36  93  68.1  45  14  8.2  0  30.1  29.9  29.7     0   
24  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
25  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
26  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
27  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
28  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
29  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
30  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
31  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
32  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
33  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
34  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
35  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
36  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
37  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
38  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
39  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
40  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
41  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
42  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
43  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
44  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
45  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
46  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
47  62.5  60  63  60.2  58  97  92.4  87  12  4.8  0  29.7  29.6  29.6  0.28   
48    59  54  58  51.1  39  97  77.4  40  22  7.9  0  30.1  29.8  29.7  0.03   
49    

In [33]:
houston_temp_24.columns = ['Temp_avg', 'Temp_min', 'Dew_max', 'Dew_avg', 'Dew_min', 'Hum_max',
       'Hum_avg', 'Hum_min', 'Wind_max', 'Wind_avg', 'Wind_min', 'Pres_max',
       'Pres_avg', 'Pres_min', 'Precipitation', 'Date']

In [34]:
houston_temp_24

Temp_avg Temp_min Dew_max Dew_avg Dew_min Hum_max Hum_avg Hum_min  \
0        57.5       53      58    46.3      36      93    68.1      45   
1        57.5       53      58    46.3      36      93    68.1      45   
2        57.5       53      58    46.3      36      93    68.1      45   
3        57.5       53      58    46.3      36      93    68.1      45   
4        57.5       53      58    46.3      36      93    68.1      45   
...       ...      ...     ...     ...     ...     ...     ...     ...   
8755     61.4       45      67    57.2      36      94    86.1      71   
8756     61.4       45      67    57.2      36      94    86.1      71   
8757     61.4       45      67    57.2      36      94    86.1      71   
8758     61.4       45      67    57.2      36      94    86.1      71   
8759     61.4       45      67    57.2      36      94    86.1      71   

     Wind_max Wind_avg Wind_min Pres_max Pres_avg Pres_min Precipitation  \
0          14      8.2        0     30.1     29.9     29.7             0   
1          14      8.2        0     30.1     29.9     29.7             0   
2          14      8.2        0     30.1     29.9     29.7             0   
3          14      8.2        0     30.1     29.9     29.7             0   
4          14      8.2        0     30.1     29.9     29.7             0   
...       ...      ...      ...      ...      ...      ...           ...   
8755       23     13.8        6     29.8     29.6     29.5          0.19   
8756       23     13.8        6     29.8     29.6     29.5          0.19   
8757       23     13.8        6     29.8     29.6     29.5          0.19   
8758       23     13.8        6     29.8     29.6     29.5          0.19   
8759       23     13.8        6     29.8     29.6     29.5          0.19   

            Date  
0       2020-1-1  
1       2020-1-1  
2       2020-1-1  
3       2020-1-1  
4       2020-1-1  
...          ...  
8755  2020-12-31  
8756  2020-12-31  
8757  2020-12-31  
8758  2020-12-31  
8759  2020-12-31  

[8760 rows x 16 columns]

In [11]:
hours = np.arange(0,24)

In [12]:
hours

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
# houston_temp_24= pd.DataFrame(np.repeat(hours, 24, axis =1  ))


In [13]:
houston_temp_24.head(50)

Temp_avg Temp_min Dew_max Dew_avg Dew_min Hum_max Hum_avg Hum_min Wind_max  \
0      57.5       53      58    46.3      36      93    68.1      45       14   
1      57.5       53      58    46.3      36      93    68.1      45       14   
2      57.5       53      58    46.3      36      93    68.1      45       14   
3      57.5       53      58    46.3      36      93    68.1      45       14   
4      57.5       53      58    46.3      36      93    68.1      45       14   
5      57.5       53      58    46.3      36      93    68.1      45       14   
6      57.5       53      58    46.3      36      93    68.1      45       14   
7      57.5       53      58    46.3      36      93    68.1      45       14   
8      57.5       53      58    46.3      36      93    68.1      45       14   
9      57.5       53      58    46.3      36      93    68.1      45       14   
10     57.5       53      58    46.3      36      93    68.1      45       14   
11     57.5       53      58    46.3      36      93    68.1      45       14   
12     57.5       53      58    46.3      36      93    68.1      45       14   
13     57.5       53      58    46.3      36      93    68.1      45       14   
14     57.5       53      58    46.3      36      93    68.1      45       14   
15     57.5       53      58    46.3      36      93    68.1      45       14   
16     57.5       53      58    46.3      36      93    68.1      45       14   
17     57.5       53      58    46.3      36      93    68.1      45       14   
18     57.5       53      58    46.3      36      93    68.1      45       14   
19     57.5       53      58    46.3      36      93    68.1      45       14   
20     57.5       53      58    46.3      36      93    68.1      45       14   
21     57.5       53      58    46.3      36      93    68.1      45       14   
22     57.5       53      58    46.3      36      93    68.1      45       14   
23     57.5       53      58    46.3      36      93    68.1      45       14   
24     62.5       60      63    60.2      58      97    92.4      87       12   
25     62.5       60      63    60.2      58      97    92.4      87       12   
26     62.5       60      63    60.2      58      97    92.4      87       12   
27     62.5       60      63    60.2      58      97    92.4      87       12   
28     62.5       60      63    60.2      58      97    92.4      87       12   
29     62.5       60      63    60.2      58      97    92.4      87       12   
30     62.5       60      63    60.2      58      97    92.4      87       12   
31     62.5       60      63    60.2      58      97    92.4      87       12   
32     62.5       60      63    60.2      58      97    92.4      87       12   
33     62.5       60      63    60.2      58      97    92.4      87       12   
34     62.5       60      63    60.2      58      97    92.4      87       12   
35     62.5       60      63    60.2      58      97    92.4      87       12   
36     62.5       60      63    60.2      58      97    92.4      87       12   
37     62.5       60      63    60.2      58      97    92.4      87       12   
38     62.5       60      63    60.2      58      97    92.4      87       12   
39     62.5       60      63    60.2      58      97    92.4      87       12   
40     62.5       60      63    60.2      58      97    92.4      87       12   
41     62.5       60      63    60.2      58      97    92.4      87       12   
42     62.5       60      63    60.2      58      97    92.4      87       12   
43     62.5       60      63    60.2      58      97    92.4      87       12   
44     62.5       60      63    60.2      58      97    92.4      87       12   
45     62.5       60      63    60.2      58      97    92.4      87       12   
46     62.5       60      63    60.2      58      97    92.4      87       12   
47     62.5       60      63    60.2      58      97    92.4      87       12   
48       59       54      58    51

In [14]:
hours_3 = []
for i in range (365):
    
    hours_3.append(hours)
hours_3
# hours_3.shape


[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 

In [16]:
hours_df = pd.DataFrame(hours_3) 

In [17]:
hours_df.shape

(365, 24)

In [18]:
hours_df

0   1   2   3   4   5   6   7   8   9   ...  14  15  16  17  18  19  20  \
0     0   1   2   3   4   5   6   7   8   9  ...  14  15  16  17  18  19  20   
1     0   1   2   3   4   5   6   7   8   9  ...  14  15  16  17  18  19  20   
2     0   1   2   3   4   5   6   7   8   9  ...  14  15  16  17  18  19  20   
3     0   1   2   3   4   5   6   7   8   9  ...  14  15  16  17  18  19  20   
4     0   1   2   3   4   5   6   7   8   9  ...  14  15  16  17  18  19  20   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
360   0   1   2   3   4   5   6   7   8   9  ...  14  15  16  17  18  19  20   
361   0   1   2   3   4   5   6   7   8   9  ...  14  15  16  17  18  19  20   
362   0   1   2   3   4   5   6   7   8   9  ...  14  15  16  17  18  19  20   
363   0   1   2   3   4   5   6   7   8   9  ...  14  15  16  17  18  19  20   
364   0   1   2   3   4   5   6   7   8   9  ...  14  15  16  17  18  19  20   

     21  22  23  
0    21  22  23  
1    21  22  23  
2    21  22  23  
3    21  22  23  
4    21  22  23  
..   ..  ..  ..  
360  21  22  23  
361  21  22  23  
362  21  22  23  
363  21  22  23  
364  21  22  23  

[365 rows x 24 columns]

In [22]:
numpy_array = hours_df.to_numpy()

In [23]:
numpy_array

array([[ 0,  1,  2, ..., 21, 22, 23],
       [ 0,  1,  2, ..., 21, 22, 23],
       [ 0,  1,  2, ..., 21, 22, 23],
       ...,
       [ 0,  1,  2, ..., 21, 22, 23],
       [ 0,  1,  2, ..., 21, 22, 23],
       [ 0,  1,  2, ..., 21, 22, 23]])

In [30]:
hours_col= numpy_array.reshape(8760, -1)

In [31]:
hours_final_df = pd.DataFrame(hours_col)

In [32]:
hours_final_df

0
0      0
1      1
2      2
3      3
4      4
...   ..
8755  19
8756  20
8757  21
8758  22
8759  23

[8760 rows x 1 columns]

In [37]:
houston_temp_24['Hour Number'] = hours_final_df

In [38]:
houston_temp_24

Temp_avg Temp_min Dew_max Dew_avg Dew_min Hum_max Hum_avg Hum_min  \
0        57.5       53      58    46.3      36      93    68.1      45   
1        57.5       53      58    46.3      36      93    68.1      45   
2        57.5       53      58    46.3      36      93    68.1      45   
3        57.5       53      58    46.3      36      93    68.1      45   
4        57.5       53      58    46.3      36      93    68.1      45   
...       ...      ...     ...     ...     ...     ...     ...     ...   
8755     61.4       45      67    57.2      36      94    86.1      71   
8756     61.4       45      67    57.2      36      94    86.1      71   
8757     61.4       45      67    57.2      36      94    86.1      71   
8758     61.4       45      67    57.2      36      94    86.1      71   
8759     61.4       45      67    57.2      36      94    86.1      71   

     Wind_max Wind_avg Wind_min Pres_max Pres_avg Pres_min Precipitation  \
0          14      8.2        0     30.1     29.9     29.7             0   
1          14      8.2        0     30.1     29.9     29.7             0   
2          14      8.2        0     30.1     29.9     29.7             0   
3          14      8.2        0     30.1     29.9     29.7             0   
4          14      8.2        0     30.1     29.9     29.7             0   
...       ...      ...      ...      ...      ...      ...           ...   
8755       23     13.8        6     29.8     29.6     29.5          0.19   
8756       23     13.8        6     29.8     29.6     29.5          0.19   
8757       23     13.8        6     29.8     29.6     29.5          0.19   
8758       23     13.8        6     29.8     29.6     29.5          0.19   
8759       23     13.8        6     29.8     29.6     29.5          0.19   

            Date  hours  Hour Number  
0       2020-1-1      0            0  
1       2020-1-1      1            1  
2       2020-1-1      2            2  
3       2020-1-1      3            3  
4       2020-1-1      4            4  
...          ...    ...          ...  
8755  2020-12-31     19           19  
8756  2020-12-31     20           20  
8757  2020-12-31     21           21  
8758  2020-12-31     22           22  
8759  2020-12-31     23           23  

[8760 rows x 18 columns]

In [39]:
del houston_temp_24['hours']
houston_temp_24

Temp_avg Temp_min Dew_max Dew_avg Dew_min Hum_max Hum_avg Hum_min  \
0        57.5       53      58    46.3      36      93    68.1      45   
1        57.5       53      58    46.3      36      93    68.1      45   
2        57.5       53      58    46.3      36      93    68.1      45   
3        57.5       53      58    46.3      36      93    68.1      45   
4        57.5       53      58    46.3      36      93    68.1      45   
...       ...      ...     ...     ...     ...     ...     ...     ...   
8755     61.4       45      67    57.2      36      94    86.1      71   
8756     61.4       45      67    57.2      36      94    86.1      71   
8757     61.4       45      67    57.2      36      94    86.1      71   
8758     61.4       45      67    57.2      36      94    86.1      71   
8759     61.4       45      67    57.2      36      94    86.1      71   

     Wind_max Wind_avg Wind_min Pres_max Pres_avg Pres_min Precipitation  \
0          14      8.2        0     30.1     29.9     29.7             0   
1          14      8.2        0     30.1     29.9     29.7             0   
2          14      8.2        0     30.1     29.9     29.7             0   
3          14      8.2        0     30.1     29.9     29.7             0   
4          14      8.2        0     30.1     29.9     29.7             0   
...       ...      ...      ...      ...      ...      ...           ...   
8755       23     13.8        6     29.8     29.6     29.5          0.19   
8756       23     13.8        6     29.8     29.6     29.5          0.19   
8757       23     13.8        6     29.8     29.6     29.5          0.19   
8758       23     13.8        6     29.8     29.6     29.5          0.19   
8759       23     13.8        6     29.8     29.6     29.5          0.19   

            Date  Hour Number  
0       2020-1-1            0  
1       2020-1-1            1  
2       2020-1-1            2  
3       2020-1-1            3  
4       2020-1-1            4  
...          ...          ...  
8755  2020-12-31           19  
8756  2020-12-31           20  
8757  2020-12-31           21  
8758  2020-12-31           22  
8759  2020-12-31           23  

[8760 rows x 17 columns]

In [41]:
houston_temp_24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Temp_avg       8760 non-null   object
 1   Temp_min       8760 non-null   object
 2   Dew_max        8760 non-null   object
 3   Dew_avg        8760 non-null   object
 4   Dew_min        8760 non-null   object
 5   Hum_max        8760 non-null   object
 6   Hum_avg        8760 non-null   object
 7   Hum_min        8760 non-null   object
 8   Wind_max       8760 non-null   object
 9   Wind_avg       8760 non-null   object
 10  Wind_min       8760 non-null   object
 11  Pres_max       8760 non-null   object
 12  Pres_avg       8760 non-null   object
 13  Pres_min       8760 non-null   object
 14  Precipitation  8760 non-null   object
 15  Date           8760 non-null   object
 16  Hour Number    8760 non-null   int64 
dtypes: int64(1), object(16)
memory usage: 1.1+ MB


In [45]:
def make_date_time_col_city(df):
    
    df['Date']= df['Date'].astype(str)
    df['Hour Number'] = df['Hour Number'].astype(str)
    df['New_datetime'] = df['Date'].map(str) + " " + df['Hour Number']
    df['Hour Number'] = df['Hour Number'].astype(int)
    
    return df

In [46]:
converted_houston_temp_24 =  make_date_time_col_city(houston_temp_24)

In [47]:
converted_houston_temp_24

Temp_avg Temp_min Dew_max Dew_avg Dew_min Hum_max Hum_avg Hum_min  \
0        57.5       53      58    46.3      36      93    68.1      45   
1        57.5       53      58    46.3      36      93    68.1      45   
2        57.5       53      58    46.3      36      93    68.1      45   
3        57.5       53      58    46.3      36      93    68.1      45   
4        57.5       53      58    46.3      36      93    68.1      45   
...       ...      ...     ...     ...     ...     ...     ...     ...   
8755     61.4       45      67    57.2      36      94    86.1      71   
8756     61.4       45      67    57.2      36      94    86.1      71   
8757     61.4       45      67    57.2      36      94    86.1      71   
8758     61.4       45      67    57.2      36      94    86.1      71   
8759     61.4       45      67    57.2      36      94    86.1      71   

     Wind_max Wind_avg Wind_min Pres_max Pres_avg Pres_min Precipitation  \
0          14      8.2        0     30.1     29.9     29.7             0   
1          14      8.2        0     30.1     29.9     29.7             0   
2          14      8.2        0     30.1     29.9     29.7             0   
3          14      8.2        0     30.1     29.9     29.7             0   
4          14      8.2        0     30.1     29.9     29.7             0   
...       ...      ...      ...      ...      ...      ...           ...   
8755       23     13.8        6     29.8     29.6     29.5          0.19   
8756       23     13.8        6     29.8     29.6     29.5          0.19   
8757       23     13.8        6     29.8     29.6     29.5          0.19   
8758       23     13.8        6     29.8     29.6     29.5          0.19   
8759       23     13.8        6     29.8     29.6     29.5          0.19   

            Date  Hour Number   New_datetime  
0       2020-1-1            0     2020-1-1 0  
1       2020-1-1            1     2020-1-1 1  
2       2020-1-1            2     2020-1-1 2  
3       2020-1-1            3     2020-1-1 3  
4       2020-1-1            4     2020-1-1 4  
...          ...          ...            ...  
8755  2020-12-31           19  2020-12-31 19  
8756  2020-12-31           20  2020-12-31 20  
8757  2020-12-31           21  2020-12-31 21  
8758  2020-12-31           22  2020-12-31 22  
8759  2020-12-31           23  2020-12-31 23  

[8760 rows x 18 columns]

In [49]:
converted_houston_temp_24['New_datetime']= converted_houston_temp_24['New_datetime'].apply(lambda x:f'{x}:00:00')

In [50]:
converted_houston_temp_24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Temp_avg       8760 non-null   object
 1   Temp_min       8760 non-null   object
 2   Dew_max        8760 non-null   object
 3   Dew_avg        8760 non-null   object
 4   Dew_min        8760 non-null   object
 5   Hum_max        8760 non-null   object
 6   Hum_avg        8760 non-null   object
 7   Hum_min        8760 non-null   object
 8   Wind_max       8760 non-null   object
 9   Wind_avg       8760 non-null   object
 10  Wind_min       8760 non-null   object
 11  Pres_max       8760 non-null   object
 12  Pres_avg       8760 non-null   object
 13  Pres_min       8760 non-null   object
 14  Precipitation  8760 non-null   object
 15  Date           8760 non-null   object
 16  Hour Number    8760 non-null   int64 
 17  New_datetime   8760 non-null   object
dtypes: int64(1), object(17)
memo

In [51]:
converted_houston_temp_24['New_datetime'] = pd.to_datetime(converted_houston_temp_24['New_datetime'],infer_datetime_format=True, format ='%m/%d/%Y %H')

In [53]:
converted_houston_temp_24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   Temp_avg       8760 non-null   object        
 1   Temp_min       8760 non-null   object        
 2   Dew_max        8760 non-null   object        
 3   Dew_avg        8760 non-null   object        
 4   Dew_min        8760 non-null   object        
 5   Hum_max        8760 non-null   object        
 6   Hum_avg        8760 non-null   object        
 7   Hum_min        8760 non-null   object        
 8   Wind_max       8760 non-null   object        
 9   Wind_avg       8760 non-null   object        
 10  Wind_min       8760 non-null   object        
 11  Pres_max       8760 non-null   object        
 12  Pres_avg       8760 non-null   object        
 13  Pres_min       8760 non-null   object        
 14  Precipitation  8760 non-null   object        
 15  Date           8760 n

In [54]:

converted_houston_temp_24.to_csv (r'/Users/cp/Desktop/capstone2/Houston_weather_hours.csv', index = False, header=True)

In [55]:
converted_houston_temp_24

Temp_avg Temp_min Dew_max Dew_avg Dew_min Hum_max Hum_avg Hum_min  \
0        57.5       53      58    46.3      36      93    68.1      45   
1        57.5       53      58    46.3      36      93    68.1      45   
2        57.5       53      58    46.3      36      93    68.1      45   
3        57.5       53      58    46.3      36      93    68.1      45   
4        57.5       53      58    46.3      36      93    68.1      45   
...       ...      ...     ...     ...     ...     ...     ...     ...   
8755     61.4       45      67    57.2      36      94    86.1      71   
8756     61.4       45      67    57.2      36      94    86.1      71   
8757     61.4       45      67    57.2      36      94    86.1      71   
8758     61.4       45      67    57.2      36      94    86.1      71   
8759     61.4       45      67    57.2      36      94    86.1      71   

     Wind_max Wind_avg Wind_min Pres_max Pres_avg Pres_min Precipitation  \
0          14      8.2        0     30.1     29.9     29.7             0   
1          14      8.2        0     30.1     29.9     29.7             0   
2          14      8.2        0     30.1     29.9     29.7             0   
3          14      8.2        0     30.1     29.9     29.7             0   
4          14      8.2        0     30.1     29.9     29.7             0   
...       ...      ...      ...      ...      ...      ...           ...   
8755       23     13.8        6     29.8     29.6     29.5          0.19   
8756       23     13.8        6     29.8     29.6     29.5          0.19   
8757       23     13.8        6     29.8     29.6     29.5          0.19   
8758       23     13.8        6     29.8     29.6     29.5          0.19   
8759       23     13.8        6     29.8     29.6     29.5          0.19   

            Date  Hour Number        New_datetime  
0       2020-1-1            0 2020-01-01 00:00:00  
1       2020-1-1            1 2020-01-01 01:00:00  
2       2020-1-1            2 2020-01-01 02:00:00  
3       2020-1-1            3 2020-01-01 03:00:00  
4       2020-1-1            4 2020-01-01 04:00:00  
...          ...          ...                 ...  
8755  2020-12-31           19 2020-12-31 19:00:00  
8756  2020-12-31           20 2020-12-31 20:00:00  
8757  2020-12-31           21 2020-12-31 21:00:00  
8758  2020-12-31           22 2020-12-31 22:00:00  
8759  2020-12-31           23 2020-12-31 23:00:00  

[8760 rows x 18 columns]